In [12]:
#importing the Libraies
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [13]:
# Reading the Dataset
dataset = pd.read_csv('CKD.csv')
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [14]:
dataset=pd.get_dummies(dataset,drop_first=True, dtype=int)
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [15]:
dataset["classification_yes"].value_counts()

classification_yes
1    249
0    150
Name: count, dtype: int64

In [16]:
indep1=dataset.drop(columns=['classification_yes'])
dep=dataset['classification_yes']
indep1.shape

(399, 27)

In [17]:
dep

0      1
1      1
2      1
3      1
4      1
      ..
394    1
395    1
396    1
397    1
398    0
Name: classification_yes, Length: 399, dtype: int32

In [18]:
#split into training set and test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(indep1, dep, test_size = 1/3, random_state = 0)

In [19]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [20]:
from sklearn.model_selection import GridSearchCV

# Define the parameter grid

param_grid = {

    'C': [0.01, 0.1, 1, 10, 100], # Regularization strength

    'penalty': ['l1', 'l2', 'elasticnet', 'none'], # Penalty type

    'solver': ['lbfgs', 'liblinear', 'saga'], # Solvers compatible with penalties

}

from sklearn.linear_model import LogisticRegression

grid = GridSearchCV(LogisticRegression(), param_grid, refit = True, verbose = 3,n_jobs=-1,scoring='f1_weighted')

grid.fit(X_train, y_train)

Fitting 5 folds for each of 60 candidates, totalling 300 fits

C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:540: FitFailedWarning:
175 fits failed out of a total of 300.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 67, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got l1 penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 67, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or None penalties, got elasticnet penalty.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1194, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 75, in _check_solver
    raise ValueError(
ValueError: Only 'saga' solver supports elasticnet penalty, got solver=liblinear.

--------------------------------------------------------------------------------
25 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1473, in wrapper
    return fit_method(estimator, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py", line 1204, in fit
    raise ValueError("l1_ratio must be specified when penalty is elasticnet.")
ValueError: l1_ratio must be specified when penalty is elasticnet.

--------------------------------------------------------------------------------
21 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l2', 'l1'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
18 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'l1', 'elasticnet'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
14 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'l2', 'elasticnet', 'l1'} or None. Got 'none' instead.

--------------------------------------------------------------------------------
22 fits failed with the following error:
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 888, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 1466, in wrapper
    estimator._validate_params()
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\base.py", line 666, in _validate_params
    validate_parameter_constraints(
  File "C:\ProgramData\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'penalty' parameter of LogisticRegression must be a str among {'elasticnet', 'l1', 'l2'} or None. Got 'none' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\ProgramData\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:1102: UserWarning: One or more of the test scores are non-finite: [       nan 0.20194378 0.48429303 0.98496077 0.92971619 0.98496077
        nan        nan        nan        nan        nan        nan
        nan 0.96262951 0.966259   0.98868958 0.95910985 0.98496077
        nan        nan        nan        nan        nan        nan
        nan 0.97751924 0.98500464 0.98876    0.97390477 0.98129068
        nan        nan        nan        nan        nan        nan
        nan 0.97763358 0.97763358 0.98880386 0.98514677 0.97763358
        nan        nan        nan        nan        nan        nan
        nan 0.96646598 0.97763358 0.98135296 0.97775352 0.97763358
        nan        nan        nan        nan        nan        nan]
  warnings.warn(

GridSearchCV(estimator=LogisticRegression(), n_jobs=-1,
             param_grid={'C': [0.01, 0.1, 1, 10, 100],
                         'penalty': ['l1', 'l2', 'elasticnet', 'none'],
                         'solver': ['lbfgs', 'liblinear', 'saga']},
             scoring='f1_weighted', verbose=3)

In [21]:
# print best parameter after tuning 
#print(grid.best_params_) 
re=grid.cv_results_
#print(re)
grid_predictions = grid.predict(X_test)

In [22]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)



# print classification report 
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [23]:
from sklearn.metrics import f1_score
f1_macro=f1_score(y_test,grid_predictions,average='weighted')
print("The f1_macro value for best parameter {}:".format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}: 0.9850141736106648

In [24]:
print(clf_report)

              precision    recall  f1-score   support

           0       0.96      1.00      0.98        51
           1       1.00      0.98      0.99        82

    accuracy                           0.98       133
   macro avg       0.98      0.99      0.98       133
weighted avg       0.99      0.98      0.99       133

In [25]:
from sklearn.metrics import roc_auc_score

roc_auc_score(y_test,grid.predict_proba(X_test)[:,1])

0.9997608799617408

In [26]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_C,param_penalty,param_solver,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.001507,4.489642e-04,0.000000,0.000000,0.01,l1,lbfgs,"{'C': 0.01, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
1,0.003754,1.339945e-03,0.004217,0.000510,0.01,l1,liblinear,"{'C': 0.01, 'penalty': 'l1', 'solver': 'liblin...",0.200200,0.189203,0.206772,0.206772,0.206772,0.201944,0.006860,25
2,0.003171,5.936550e-04,0.004415,0.000585,0.01,l1,saga,"{'C': 0.01, 'penalty': 'l1', 'solver': 'saga'}",0.486532,0.501410,0.477841,0.477841,0.477841,0.484293,0.009196,24
3,0.005366,1.879766e-03,0.004726,0.001409,0.01,l2,lbfgs,"{'C': 0.01, 'penalty': 'l2', 'solver': 'lbfgs'}",1.000000,0.981014,0.962573,1.000000,0.981217,0.984961,0.014023,6
4,0.003420,1.585652e-03,0.006092,0.001477,0.01,l2,liblinear,"{'C': 0.01, 'penalty': 'l2', 'solver': 'liblin...",0.890759,0.944161,0.888515,0.962573,0.962573,0.929716,0.033416,23
5,0.011247,1.280328e-03,0.004095,0.000546,0.01,l2,saga,"{'C': 0.01, 'penalty': 'l2', 'solver': 'saga'}",1.000000,0.981014,0.962573,1.000000,0.981217,0.984961,0.014023,6
6,0.001421,8.159464e-04,0.000000,0.000000,0.01,elasticnet,lbfgs,"{'C': 0.01, 'penalty': 'elasticnet', 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
7,0.000000,0.000000e+00,0.000000,0.000000,0.01,elasticnet,liblinear,"{'C': 0.01, 'penalty': 'elasticnet', 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
8,0.000985,1.514062e-03,0.000000,0.000000,0.01,elasticnet,saga,"{'C': 0.01, 'penalty': 'elasticnet', 'solver':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
9,0.000909,3.738305e-04,0.000000,0.000000,0.01,none,lbfgs,"{'C': 0.01, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
10,0.000800,4.001938e-04,0.000000,0.000000,0.01,none,liblinear,"{'C': 0.01, 'penalty': 'none', 'solver': 'libl...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
11,0.001000,3.568323e-07,0.000000,0.000000,0.01,none,saga,"{'C': 0.01, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
12,0.000903,4.928937e-04,0.000000,0.000000,0.10,l1,lbfgs,"{'C': 0.1, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
13,0.002506,6.406218e-04,0.005823,0.000411,0.10,l1,liblinear,"{'C': 0.1, 'penalty': 'l1', 'solver': 'libline...",0.981569,0.962264,0.925524,0.962573,0.981217,0.962630,0.020402,21
14,0.028761,1.341901e-03,0.005068,0.000827,0.10,l1,saga,"{'C': 0.1, 'penalty': 'l1', 'solver': 'saga'}",0.962963,0.981014,0.944023,0.981031,0.962264,0.966259,0.013836,20
15,0.005376,7.728576e-04,0.004018,0.000965,0.10,l2,lbfgs,"{'C': 0.1, 'penalty': 'l2', 'solver': 'lbfgs'}",1.000000,0.981014,0.981217,1.000000,0.981217,0.988690,0.009235,3
16,0.003228,5.139610e-04,0.004737,0.000633,0.10,l2,liblinear,"{'C': 0.1, 'penalty': 'l2', 'solver': 'libline...",0.945100,0.962636,0.944023,0.981217,0.962573,0.959110,0.013690,22
17,0.021544,1.478831e-03,0.005110,0.000957,0.10,l2,saga,"{'C': 0.1, 'penalty': 'l2', 'solver': 'saga'}",1.000000,0.981014,0.962573,1.000000,0.981217,0.984961,0.014023,6
18,0.001206,9.846312e-04,0.000000,0.000000,0.10,elasticnet,lbfgs,"{'C': 0.1, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
19,0.000824,1.009073e-03,0.000000,0.000000,0.10,elasticnet,liblinear,"{'C': 0.1, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
20,0.000403,8.052826e-04,0.000000,0.000000,0.10,elasticnet,saga,"{'C': 0.1, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
21,0.000403,8.055687e-04,0.000000,0.000000,0.10,none,lbfgs,"{'C': 0.1, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
22,0.001204,9.828009e-04,0.000000,0.000000,0.10,none,liblinear,"{'C': 0.1, 'penalty': 'none', 'solver': 'libli...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
23,0.000752,9.240857e-04,0.000000,0.000000,0.10,none,saga,"{'C': 0.1, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
24,0.001604,8.021118e-04,0.000000,0.000000,1.00,l1,lbfgs,"{'C': 1, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
25,0.002613,7.871070e-04,0.004575,0.000405,1.00,l1,liblinear,"{'C': 1, 'penalty': 'l1', 'solver': 'liblinear'}",1.000000,0.981233,0.981217,0.962573,0.962573,0.977519,0.013997,17
26,0.030700,9.500466e-04,0.004940,0.000983,1.00,l1,saga,"{'C': 1, 'penalty': 'l1', 'solver': 'saga'}",1.000000,0.981233,0.981217,1.000000,0.962573,0.985005,0.014010,5
27,0.006816,8.988449e-04,0.005523,0.001545,1.00,l2,lbfgs,"{'C': 1, 'penalty': 'l2', 'solver': 'lbfgs'}",0.981569,0.981014,0.981217,1.000000,1.000000,0.988760,0.009179,2
28,0.003915,2.124737e-03,0.004655,0.000869,1.00,l2,liblinear,"{'C': 1, 'penalty': 'l2', 'solver': 'liblinear'}",0.963284,0.981233,0.962573,0.981217,0.981217,0.973905,0.008965,18
29,0.021575,1.913488e-03,0.005076,0.001490,1.00,l2,saga,"{'C': 1, 'penalty': 'l2', 'solver': 'saga'}",0.981569,0.981233,0.981217,0.981217,0.981217,0.981291,0.000139,10
30,0.001122,9.369882e-04,0.000000,0.000000,1.00,elasticnet,lbfgs,"{'C': 1, 'penalty': 'elasticnet', 'solver': 'l...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
31,0.000403,8.052826e-04,0.000000,0.000000,1.00,elasticnet,liblinear,"{'C': 1, 'penalty': 'elasticnet', 'solver': 'l...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
32,0.000719,8.983989e-04,0.000000,0.000000,1.00,elasticnet,saga,"{'C': 1, 'penalty': 'elasticnet', 'solver': 's...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
33,0.001273,1.046899e-03,0.000000,0.000000,1.00,none,lbfgs,"{'C': 1, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
34,0.002009,1.360449e-06,0.000000,0.000000,1.00,none,liblinear,"{'C': 1, 'penalty': 'none', 'solver': 'libline...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
35,0.000803,9.837545e-04,0.000000,0.000000,1.00,none,saga,"{'C': 1, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
36,0.001443,8.350568e-04,0.000000,0.000000,10.00,l1,lbfgs,"{'C': 10, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
37,0.005064,1.081785e-03,0.003987,0.000592,10.00,l1,liblinear,"{'C': 10, 'penalty': 'l1', 'solver': 'liblinear'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,12
38,0.030777,2.464947e-03,0.005516,0.001014,10.00,l1,saga,"{'C': 10, 'penalty': 'l1', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,12
39,0.008525,6.866473e-04,0.005232,0.001051,10.00,l2,lbfgs,"{'C': 10, 'penalty': 'l2', 'solver': 'lbfgs'}",0.981569,0.981233,0.981217,1.000000,1.000000,0.988804,0.009142,1
40,0.004275,1.022931e-03,0.004196,0.000486,10.00,l2,liblinear,"{'C': 10, 'penalty': 'l2', 'solver': 'liblinear'}",0.963284,0.981233,0.981217,1.000000,1.000000,0.985147,0.013784,4
41,0.021582,1.416161e-03,0.004931,0.000974,10.00,l2,saga,"{'C': 10, 'penalty': 'l2', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,12
42,0.000399,4.885782e-04,0.000000,0.000000,10.00,elasticnet,lbfgs,"{'C': 10, 'penalty': 'elasticnet', 'solver': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
43,0.000907,1.122067e-03,0.000000,0.000000,10.00,elasticnet,liblinear,"{'C': 10, 'penalty': 'elasticnet', 'solver': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
44,0.000704,6.037195e-04,0.000000,0.000000,10.00,elasticnet,saga,"{'C': 10, 'penalty': 'elasticnet', 'solver': '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
45,0.001000,6.290495e-04,0.000000,0.000000,10.00,none,lbfgs,"{'C': 10, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
46,0.000900,4.911339e-04,0.000000,0.000000,10.00,none,liblinear,"{'C': 10, 'penalty': 'none', 'solver': 'liblin...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
47,0.001018,6.602558e-04,0.000000,0.000000,10.00,none,saga,"{'C': 10, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
48,0.001419,1.030089e-03,0.000000,0.000000,100.00,l1,lbfgs,"{'C': 100, 'penalty': 'l1', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
49,0.005414,1.578390e-03,0.004773,0.000815,100.00,l1,liblinear,"{'C': 100, 'penalty': 'l1', 'solver': 'libline...",0.963284,0.981233,0.944023,0.962573,0.981217,0.966466,0.013890,19
50,0.032804,6.558880e-04,0.004332,0.001194,100.00,l1,saga,"{'C': 100, 'penalty': 'l1', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,12
51,0.009145,1.953933e-03,0.005188,0.000565,100.00,l2,lbfgs,"{'C': 100, 'penalty': 'l2', 'solver': 'lbfgs'}",0.963284,0.962264,0.981217,1.000000,1.000000,0.981353,0.016651,9
52,0.004636,5.689823e-04,0.005397,0.000967,100.00,l2,liblinear,"{'C': 100, 'penalty': 'l2', 'solver': 'libline...",0.945100,0.981233,0.981217,0.981217,1.000000,0.977754,0.017873,11
53,0.023683,1.259794e-03,0.003599,0.001959,100.00,l2,saga,"{'C': 100, 'penalty': 'l2', 'solver': 'saga'}",0.963284,0.981233,0.981217,0.981217,0.981217,0.977634,0.007175,12
54,0.000744,7.451385e-04,0.000000,0.000000,100.00,elasticnet,lbfgs,"{'C': 100, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
55,0.000916,9.164968e-04,0.000000,0.000000,100.00,elasticnet,liblinear,"{'C': 100, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
56,0.001065,9.073708e-04,0.000000,0.000000,100.00,elasticnet,saga,"{'C': 100, 'penalty': 'elasticnet', 'solver': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
57,0.000000,0.000000e+00,0.000000,0.000000,100.00,none,lbfgs,"{'C': 100, 'penalty': 'none', 'solver': 'lbfgs'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
58,0.001968,3.936005e-03,0.000000,0.000000,100.00,none,liblinear,"{'C': 100, 'penalty': 'none', 'solver': 'libli...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26
59,0.000882,1.764393e-03,0.000000,0.000000,100.00,none,saga,"{'C': 100, 'penalty': 'none', 'solver': 'saga'}",NaN,NaN,NaN,NaN,NaN,NaN,NaN,26

In [27]:
print(cm)

[[51  0]
 [ 2 80]]